version: "2"
run:
  issues-exit-code: 1
linters:
  enable:
    - asciicheck
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - importas
    - misspell
    - modernize
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G115
    modernize:
      disable:
        # Simplify code by using go1.26's new(expr).
        - newexpr
        # Suggest replacing omitempty with omitzero for struct fields.
        - omitzero
    revive:
      rules:
        - name: dot-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - prealloc
        path: _test\.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
