/*
Copyright 2026 Chainguard, Inc.
SPDX-License-Identifier: Apache-2.0
*/

package metapathreconciler

// ReasoningSummarySnippet is a ready-made PR-body template fragment rendering
// the agent's extended-thinking summary as a collapsed details block. It
// renders nothing when the run produced no reasoning (extended thinking
// disabled, or a run that emitted none), so appending it to a bot's body
// template is a zero-risk opt-in: PRs from runs without reasoning render
// exactly as before.
//
// Usage — concatenate into the body template passed to the changemanager:
//
//	prBodyTemplate = "...existing body..." +
//		metapathreconciler.ReasoningSummarySnippet +
//		"\n\n---\n*Generated by {{.Identity}}*"
//
// Keep in sync with the equivalent snippet in metareconciler and
// linearreconciler/metareconciler.
const ReasoningSummarySnippet = "{{if .ReasoningSummary}}\n\n---\n<details>\n<summary>Agent reasoning</summary>\n\n{{.ReasoningSummary}}\n</details>{{end}}"

// reasoningSummaryMaxChars caps the combined size of the reasoning summary
// stored on PRData. Kept small so the summary reads as a quick orientation
// aid rather than a full transcript dump.
const reasoningSummaryMaxChars = 400
