/*
Copyright 2026 Chainguard, Inc.
SPDX-License-Identifier: Apache-2.0
*/

package changemanager

import (
	"strings"
	"testing"
	"text/template"
	"unicode/utf8"

	"github.com/google/go-cmp/cmp"
)

func TestFitPRBody(t *testing.T) {
	const suffix = "\n\n> **Note:** apply the skip label to take over."
	const tail = "\n\n<!--bot-pr-data-->\n<!--\n{\"Data\":{}}\n-->\n<!--/bot-pr-data-->"

	tests := []struct {
		name     string
		rendered string
		// wantSame asserts the body is the plain concatenation.
		wantSame bool
	}{
		{
			name:     "fits untouched",
			rendered: "Automated fixes.\n\n<details>\n<summary>Findings (1)</summary>\n\nfoo\n</details>",
			wantSame: true,
		},
		{
			name:     "exactly at the limit is untouched",
			rendered: strings.Repeat("a", maxPRBodyBytes-len(suffix)-len(tail)),
			wantSame: true,
		},
		{
			name:     "one byte over is truncated",
			rendered: strings.Repeat("a", maxPRBodyBytes-len(suffix)-len(tail)+1),
		},
		{
			name:     "oversized findings block is cut and closed",
			rendered: "Automated fixes.\n\n<details>\n<summary>Findings (900)</summary>\n\n" + strings.Repeat("**ci-check** — `golangci-lint`\n\nundefined: foo\n\n", 2000) + "</details>\n---\n*Generated by bot*",
		},
		{
			name:     "cut lands on a multi-byte rune",
			rendered: strings.Repeat("é", maxPRBodyBytes),
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := fitPRBody(t.Context(), tc.rendered, suffix, tail)

			if tc.wantSame {
				if diff := cmp.Diff(tc.rendered+suffix+tail, got); diff != "" {
					t.Fatalf("fitPRBody changed a body that fits (-want, +got):\n%s", diff)
				}
				return
			}
			if len(got) > maxPRBodyBytes {
				t.Errorf("len(body): got = %d, want <= %d", len(got), maxPRBodyBytes)
			}
			if !strings.HasSuffix(got, suffix+tail) {
				t.Errorf("body does not end with the suffix and data block: %q", got[max(len(got)-200, 0):])
			}
			if !strings.Contains(got, truncationMarker) {
				t.Errorf("truncated body lacks the marker %q", truncationMarker)
			}
			if !utf8.ValidString(got) {
				t.Error("truncated body is not valid UTF-8")
			}
			if opens, closes := strings.Count(got, detailsOpen), strings.Count(got, "</details>"); opens != closes {
				t.Errorf("<details> blocks: got %d open and %d close tags, want balanced", opens, closes)
			}
		})
	}
}

// TestFitPRBodyPreservesEmbeddedData checks that Extract reads the same data back
// from a truncated body: the cut only ever removes rendered template text.
func TestFitPRBodyPreservesEmbeddedData(t *testing.T) {
	cm, err := New[testData]("bot",
		template.Must(template.New("title").Parse("{{.PackageName}}")),
		template.Must(template.New("body").Parse("{{.PackageName}}")))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	want := &testData{PackageName: "pkg", Version: "v1.2.3", Commit: "abc123"}
	tail, err := cm.templateExecutor.Embed("", &embeddedData[testData]{Data: *want})
	if err != nil {
		t.Fatalf("Embed: %v", err)
	}

	body := fitPRBody(t.Context(), strings.Repeat("finding\n", maxPRBodyBytes), "\n\nnote", tail)
	if len(body) > maxPRBodyBytes {
		t.Fatalf("len(body): got = %d, want <= %d", len(body), maxPRBodyBytes)
	}
	got, err := cm.Extract(body)
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("Extract (-want, +got):\n%s", diff)
	}
}
